// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: student.proto

package com.example.hotfix.note.class10.protobuf;

public final class _StudentSerializable {
  private _StudentSerializable() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface _StudentOrBuilder extends
      // @@protoc_insertion_point(interface_extends:_Student)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *指定字段的类型 定义字段的编号，在Protocol Buffers中，字段的编号非常重要，字段名仅仅是作为参考和生成代码用。需要注意的是字段的编号区间范围，其中19000 ～ 19999被Protocol Buffers作为保留字段
     * </pre>
     *
     * <code>string name = 1;</code>
     */
    String getName();
    /**
     * <pre>
     *指定字段的类型 定义字段的编号，在Protocol Buffers中，字段的编号非常重要，字段名仅仅是作为参考和生成代码用。需要注意的是字段的编号区间范围，其中19000 ～ 19999被Protocol Buffers作为保留字段
     * </pre>
     *
     * <code>string name = 1;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>string sax = 2;</code>
     */
    String getSax();
    /**
     * <code>string sax = 2;</code>
     */
    com.google.protobuf.ByteString
        getSaxBytes();

    /**
     * <code>int32 age = 3;</code>
     */
    int getAge();

    /**
     * <pre>
     *required指定该字段必须赋值，禁止为空（在v3中该约束被移除）；optional指定字段为可选字段，可以为空，对于optional字段还可以使用[default]指定默认值，如果没有指定，则会使用字段类型的默认值
     * </pre>
     *
     * <code>repeated ._Course courses = 4;</code>
     */
    java.util.List<com.zero.serializabledemo.protobuf._StudentSerializable._Course> 
        getCoursesList();
    /**
     * <pre>
     *required指定该字段必须赋值，禁止为空（在v3中该约束被移除）；optional指定字段为可选字段，可以为空，对于optional字段还可以使用[default]指定默认值，如果没有指定，则会使用字段类型的默认值
     * </pre>
     *
     * <code>repeated ._Course courses = 4;</code>
     */
    com.zero.serializabledemo.protobuf._StudentSerializable._Course getCourses(int index);
    /**
     * <pre>
     *required指定该字段必须赋值，禁止为空（在v3中该约束被移除）；optional指定字段为可选字段，可以为空，对于optional字段还可以使用[default]指定默认值，如果没有指定，则会使用字段类型的默认值
     * </pre>
     *
     * <code>repeated ._Course courses = 4;</code>
     */
    int getCoursesCount();
    /**
     * <pre>
     *required指定该字段必须赋值，禁止为空（在v3中该约束被移除）；optional指定字段为可选字段，可以为空，对于optional字段还可以使用[default]指定默认值，如果没有指定，则会使用字段类型的默认值
     * </pre>
     *
     * <code>repeated ._Course courses = 4;</code>
     */
    java.util.List<? extends com.zero.serializabledemo.protobuf._StudentSerializable._CourseOrBuilder> 
        getCoursesOrBuilderList();
    /**
     * <pre>
     *required指定该字段必须赋值，禁止为空（在v3中该约束被移除）；optional指定字段为可选字段，可以为空，对于optional字段还可以使用[default]指定默认值，如果没有指定，则会使用字段类型的默认值
     * </pre>
     *
     * <code>repeated ._Course courses = 4;</code>
     */
    com.zero.serializabledemo.protobuf._StudentSerializable._CourseOrBuilder getCoursesOrBuilder(
        int index);
  }
  /**
   * <pre>
   * message 确定消息命名
   * </pre>
   *
   * Protobuf type {@code _Student}
   */
  public  static final class _Student extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:_Student)
      _StudentOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use _Student.newBuilder() to construct.
    private _Student(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private _Student() {
      name_ = "";
      sax_ = "";
      courses_ = java.util.Collections.emptyList();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private _Student(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();

              sax_ = s;
              break;
            }
            case 24: {

              age_ = input.readInt32();
              break;
            }
            case 34: {
              if (!((mutable_bitField0_ & 0x00000008) != 0)) {
                courses_ = new java.util.ArrayList<com.zero.serializabledemo.protobuf._StudentSerializable._Course>();
                mutable_bitField0_ |= 0x00000008;
              }
              courses_.add(
                  input.readMessage(com.zero.serializabledemo.protobuf._StudentSerializable._Course.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000008) != 0)) {
          courses_ = java.util.Collections.unmodifiableList(courses_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.zero.serializabledemo.protobuf._StudentSerializable.internal_static__Student_descriptor;
    }

    @Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.zero.serializabledemo.protobuf._StudentSerializable.internal_static__Student_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.zero.serializabledemo.protobuf._StudentSerializable._Student.class, com.zero.serializabledemo.protobuf._StudentSerializable._Student.Builder.class);
    }

    private int bitField0_;
    public static final int NAME_FIELD_NUMBER = 1;
    private volatile Object name_;
    /**
     * <pre>
     *指定字段的类型 定义字段的编号，在Protocol Buffers中，字段的编号非常重要，字段名仅仅是作为参考和生成代码用。需要注意的是字段的编号区间范围，其中19000 ～ 19999被Protocol Buffers作为保留字段
     * </pre>
     *
     * <code>string name = 1;</code>
     */
    public String getName() {
      Object ref = name_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *指定字段的类型 定义字段的编号，在Protocol Buffers中，字段的编号非常重要，字段名仅仅是作为参考和生成代码用。需要注意的是字段的编号区间范围，其中19000 ～ 19999被Protocol Buffers作为保留字段
     * </pre>
     *
     * <code>string name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SAX_FIELD_NUMBER = 2;
    private volatile Object sax_;
    /**
     * <code>string sax = 2;</code>
     */
    public String getSax() {
      Object ref = sax_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        sax_ = s;
        return s;
      }
    }
    /**
     * <code>string sax = 2;</code>
     */
    public com.google.protobuf.ByteString
        getSaxBytes() {
      Object ref = sax_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        sax_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int AGE_FIELD_NUMBER = 3;
    private int age_;
    /**
     * <code>int32 age = 3;</code>
     */
    public int getAge() {
      return age_;
    }

    public static final int COURSES_FIELD_NUMBER = 4;
    private java.util.List<com.zero.serializabledemo.protobuf._StudentSerializable._Course> courses_;
    /**
     * <pre>
     *required指定该字段必须赋值，禁止为空（在v3中该约束被移除）；optional指定字段为可选字段，可以为空，对于optional字段还可以使用[default]指定默认值，如果没有指定，则会使用字段类型的默认值
     * </pre>
     *
     * <code>repeated ._Course courses = 4;</code>
     */
    public java.util.List<com.zero.serializabledemo.protobuf._StudentSerializable._Course> getCoursesList() {
      return courses_;
    }
    /**
     * <pre>
     *required指定该字段必须赋值，禁止为空（在v3中该约束被移除）；optional指定字段为可选字段，可以为空，对于optional字段还可以使用[default]指定默认值，如果没有指定，则会使用字段类型的默认值
     * </pre>
     *
     * <code>repeated ._Course courses = 4;</code>
     */
    public java.util.List<? extends com.zero.serializabledemo.protobuf._StudentSerializable._CourseOrBuilder> 
        getCoursesOrBuilderList() {
      return courses_;
    }
    /**
     * <pre>
     *required指定该字段必须赋值，禁止为空（在v3中该约束被移除）；optional指定字段为可选字段，可以为空，对于optional字段还可以使用[default]指定默认值，如果没有指定，则会使用字段类型的默认值
     * </pre>
     *
     * <code>repeated ._Course courses = 4;</code>
     */
    public int getCoursesCount() {
      return courses_.size();
    }
    /**
     * <pre>
     *required指定该字段必须赋值，禁止为空（在v3中该约束被移除）；optional指定字段为可选字段，可以为空，对于optional字段还可以使用[default]指定默认值，如果没有指定，则会使用字段类型的默认值
     * </pre>
     *
     * <code>repeated ._Course courses = 4;</code>
     */
    public com.zero.serializabledemo.protobuf._StudentSerializable._Course getCourses(int index) {
      return courses_.get(index);
    }
    /**
     * <pre>
     *required指定该字段必须赋值，禁止为空（在v3中该约束被移除）；optional指定字段为可选字段，可以为空，对于optional字段还可以使用[default]指定默认值，如果没有指定，则会使用字段类型的默认值
     * </pre>
     *
     * <code>repeated ._Course courses = 4;</code>
     */
    public com.zero.serializabledemo.protobuf._StudentSerializable._CourseOrBuilder getCoursesOrBuilder(
        int index) {
      return courses_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
      }
      if (!getSaxBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, sax_);
      }
      if (age_ != 0) {
        output.writeInt32(3, age_);
      }
      for (int i = 0; i < courses_.size(); i++) {
        output.writeMessage(4, courses_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
      }
      if (!getSaxBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, sax_);
      }
      if (age_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, age_);
      }
      for (int i = 0; i < courses_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, courses_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.zero.serializabledemo.protobuf._StudentSerializable._Student)) {
        return super.equals(obj);
      }
      com.zero.serializabledemo.protobuf._StudentSerializable._Student other = (com.zero.serializabledemo.protobuf._StudentSerializable._Student) obj;

      if (!getName()
          .equals(other.getName())) return false;
      if (!getSax()
          .equals(other.getSax())) return false;
      if (getAge()
          != other.getAge()) return false;
      if (!getCoursesList()
          .equals(other.getCoursesList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + SAX_FIELD_NUMBER;
      hash = (53 * hash) + getSax().hashCode();
      hash = (37 * hash) + AGE_FIELD_NUMBER;
      hash = (53 * hash) + getAge();
      if (getCoursesCount() > 0) {
        hash = (37 * hash) + COURSES_FIELD_NUMBER;
        hash = (53 * hash) + getCoursesList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.zero.serializabledemo.protobuf._StudentSerializable._Student parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zero.serializabledemo.protobuf._StudentSerializable._Student parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zero.serializabledemo.protobuf._StudentSerializable._Student parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zero.serializabledemo.protobuf._StudentSerializable._Student parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zero.serializabledemo.protobuf._StudentSerializable._Student parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zero.serializabledemo.protobuf._StudentSerializable._Student parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zero.serializabledemo.protobuf._StudentSerializable._Student parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.zero.serializabledemo.protobuf._StudentSerializable._Student parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.zero.serializabledemo.protobuf._StudentSerializable._Student parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.zero.serializabledemo.protobuf._StudentSerializable._Student parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.zero.serializabledemo.protobuf._StudentSerializable._Student parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.zero.serializabledemo.protobuf._StudentSerializable._Student parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.zero.serializabledemo.protobuf._StudentSerializable._Student prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * message 确定消息命名
     * </pre>
     *
     * Protobuf type {@code _Student}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:_Student)
        com.zero.serializabledemo.protobuf._StudentSerializable._StudentOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.zero.serializabledemo.protobuf._StudentSerializable.internal_static__Student_descriptor;
      }

      @Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.zero.serializabledemo.protobuf._StudentSerializable.internal_static__Student_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.zero.serializabledemo.protobuf._StudentSerializable._Student.class, com.zero.serializabledemo.protobuf._StudentSerializable._Student.Builder.class);
      }

      // Construct using com.zero.serializabledemo.protobuf._StudentSerializable._Student.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getCoursesFieldBuilder();
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        name_ = "";

        sax_ = "";

        age_ = 0;

        if (coursesBuilder_ == null) {
          courses_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
        } else {
          coursesBuilder_.clear();
        }
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.zero.serializabledemo.protobuf._StudentSerializable.internal_static__Student_descriptor;
      }

      @Override
      public com.zero.serializabledemo.protobuf._StudentSerializable._Student getDefaultInstanceForType() {
        return com.zero.serializabledemo.protobuf._StudentSerializable._Student.getDefaultInstance();
      }

      @Override
      public com.zero.serializabledemo.protobuf._StudentSerializable._Student build() {
        com.zero.serializabledemo.protobuf._StudentSerializable._Student result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public com.zero.serializabledemo.protobuf._StudentSerializable._Student buildPartial() {
        com.zero.serializabledemo.protobuf._StudentSerializable._Student result = new com.zero.serializabledemo.protobuf._StudentSerializable._Student(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.name_ = name_;
        result.sax_ = sax_;
        result.age_ = age_;
        if (coursesBuilder_ == null) {
          if (((bitField0_ & 0x00000008) != 0)) {
            courses_ = java.util.Collections.unmodifiableList(courses_);
            bitField0_ = (bitField0_ & ~0x00000008);
          }
          result.courses_ = courses_;
        } else {
          result.courses_ = coursesBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.zero.serializabledemo.protobuf._StudentSerializable._Student) {
          return mergeFrom((com.zero.serializabledemo.protobuf._StudentSerializable._Student)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.zero.serializabledemo.protobuf._StudentSerializable._Student other) {
        if (other == com.zero.serializabledemo.protobuf._StudentSerializable._Student.getDefaultInstance()) return this;
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (!other.getSax().isEmpty()) {
          sax_ = other.sax_;
          onChanged();
        }
        if (other.getAge() != 0) {
          setAge(other.getAge());
        }
        if (coursesBuilder_ == null) {
          if (!other.courses_.isEmpty()) {
            if (courses_.isEmpty()) {
              courses_ = other.courses_;
              bitField0_ = (bitField0_ & ~0x00000008);
            } else {
              ensureCoursesIsMutable();
              courses_.addAll(other.courses_);
            }
            onChanged();
          }
        } else {
          if (!other.courses_.isEmpty()) {
            if (coursesBuilder_.isEmpty()) {
              coursesBuilder_.dispose();
              coursesBuilder_ = null;
              courses_ = other.courses_;
              bitField0_ = (bitField0_ & ~0x00000008);
              coursesBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getCoursesFieldBuilder() : null;
            } else {
              coursesBuilder_.addAllMessages(other.courses_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.zero.serializabledemo.protobuf._StudentSerializable._Student parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.zero.serializabledemo.protobuf._StudentSerializable._Student) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private Object name_ = "";
      /**
       * <pre>
       *指定字段的类型 定义字段的编号，在Protocol Buffers中，字段的编号非常重要，字段名仅仅是作为参考和生成代码用。需要注意的是字段的编号区间范围，其中19000 ～ 19999被Protocol Buffers作为保留字段
       * </pre>
       *
       * <code>string name = 1;</code>
       */
      public String getName() {
        Object ref = name_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *指定字段的类型 定义字段的编号，在Protocol Buffers中，字段的编号非常重要，字段名仅仅是作为参考和生成代码用。需要注意的是字段的编号区间范围，其中19000 ～ 19999被Protocol Buffers作为保留字段
       * </pre>
       *
       * <code>string name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *指定字段的类型 定义字段的编号，在Protocol Buffers中，字段的编号非常重要，字段名仅仅是作为参考和生成代码用。需要注意的是字段的编号区间范围，其中19000 ～ 19999被Protocol Buffers作为保留字段
       * </pre>
       *
       * <code>string name = 1;</code>
       */
      public Builder setName(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *指定字段的类型 定义字段的编号，在Protocol Buffers中，字段的编号非常重要，字段名仅仅是作为参考和生成代码用。需要注意的是字段的编号区间范围，其中19000 ～ 19999被Protocol Buffers作为保留字段
       * </pre>
       *
       * <code>string name = 1;</code>
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *指定字段的类型 定义字段的编号，在Protocol Buffers中，字段的编号非常重要，字段名仅仅是作为参考和生成代码用。需要注意的是字段的编号区间范围，其中19000 ～ 19999被Protocol Buffers作为保留字段
       * </pre>
       *
       * <code>string name = 1;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private Object sax_ = "";
      /**
       * <code>string sax = 2;</code>
       */
      public String getSax() {
        Object ref = sax_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          sax_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string sax = 2;</code>
       */
      public com.google.protobuf.ByteString
          getSaxBytes() {
        Object ref = sax_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          sax_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string sax = 2;</code>
       */
      public Builder setSax(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        sax_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string sax = 2;</code>
       */
      public Builder clearSax() {
        
        sax_ = getDefaultInstance().getSax();
        onChanged();
        return this;
      }
      /**
       * <code>string sax = 2;</code>
       */
      public Builder setSaxBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        sax_ = value;
        onChanged();
        return this;
      }

      private int age_ ;
      /**
       * <code>int32 age = 3;</code>
       */
      public int getAge() {
        return age_;
      }
      /**
       * <code>int32 age = 3;</code>
       */
      public Builder setAge(int value) {
        
        age_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 age = 3;</code>
       */
      public Builder clearAge() {
        
        age_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<com.zero.serializabledemo.protobuf._StudentSerializable._Course> courses_ =
        java.util.Collections.emptyList();
      private void ensureCoursesIsMutable() {
        if (!((bitField0_ & 0x00000008) != 0)) {
          courses_ = new java.util.ArrayList<com.zero.serializabledemo.protobuf._StudentSerializable._Course>(courses_);
          bitField0_ |= 0x00000008;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.zero.serializabledemo.protobuf._StudentSerializable._Course, com.zero.serializabledemo.protobuf._StudentSerializable._Course.Builder, com.zero.serializabledemo.protobuf._StudentSerializable._CourseOrBuilder> coursesBuilder_;

      /**
       * <pre>
       *required指定该字段必须赋值，禁止为空（在v3中该约束被移除）；optional指定字段为可选字段，可以为空，对于optional字段还可以使用[default]指定默认值，如果没有指定，则会使用字段类型的默认值
       * </pre>
       *
       * <code>repeated ._Course courses = 4;</code>
       */
      public java.util.List<com.zero.serializabledemo.protobuf._StudentSerializable._Course> getCoursesList() {
        if (coursesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(courses_);
        } else {
          return coursesBuilder_.getMessageList();
        }
      }
      /**
       * <pre>
       *required指定该字段必须赋值，禁止为空（在v3中该约束被移除）；optional指定字段为可选字段，可以为空，对于optional字段还可以使用[default]指定默认值，如果没有指定，则会使用字段类型的默认值
       * </pre>
       *
       * <code>repeated ._Course courses = 4;</code>
       */
      public int getCoursesCount() {
        if (coursesBuilder_ == null) {
          return courses_.size();
        } else {
          return coursesBuilder_.getCount();
        }
      }
      /**
       * <pre>
       *required指定该字段必须赋值，禁止为空（在v3中该约束被移除）；optional指定字段为可选字段，可以为空，对于optional字段还可以使用[default]指定默认值，如果没有指定，则会使用字段类型的默认值
       * </pre>
       *
       * <code>repeated ._Course courses = 4;</code>
       */
      public com.zero.serializabledemo.protobuf._StudentSerializable._Course getCourses(int index) {
        if (coursesBuilder_ == null) {
          return courses_.get(index);
        } else {
          return coursesBuilder_.getMessage(index);
        }
      }
      /**
       * <pre>
       *required指定该字段必须赋值，禁止为空（在v3中该约束被移除）；optional指定字段为可选字段，可以为空，对于optional字段还可以使用[default]指定默认值，如果没有指定，则会使用字段类型的默认值
       * </pre>
       *
       * <code>repeated ._Course courses = 4;</code>
       */
      public Builder setCourses(
          int index, com.zero.serializabledemo.protobuf._StudentSerializable._Course value) {
        if (coursesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCoursesIsMutable();
          courses_.set(index, value);
          onChanged();
        } else {
          coursesBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       *required指定该字段必须赋值，禁止为空（在v3中该约束被移除）；optional指定字段为可选字段，可以为空，对于optional字段还可以使用[default]指定默认值，如果没有指定，则会使用字段类型的默认值
       * </pre>
       *
       * <code>repeated ._Course courses = 4;</code>
       */
      public Builder setCourses(
          int index, com.zero.serializabledemo.protobuf._StudentSerializable._Course.Builder builderForValue) {
        if (coursesBuilder_ == null) {
          ensureCoursesIsMutable();
          courses_.set(index, builderForValue.build());
          onChanged();
        } else {
          coursesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       *required指定该字段必须赋值，禁止为空（在v3中该约束被移除）；optional指定字段为可选字段，可以为空，对于optional字段还可以使用[default]指定默认值，如果没有指定，则会使用字段类型的默认值
       * </pre>
       *
       * <code>repeated ._Course courses = 4;</code>
       */
      public Builder addCourses(com.zero.serializabledemo.protobuf._StudentSerializable._Course value) {
        if (coursesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCoursesIsMutable();
          courses_.add(value);
          onChanged();
        } else {
          coursesBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <pre>
       *required指定该字段必须赋值，禁止为空（在v3中该约束被移除）；optional指定字段为可选字段，可以为空，对于optional字段还可以使用[default]指定默认值，如果没有指定，则会使用字段类型的默认值
       * </pre>
       *
       * <code>repeated ._Course courses = 4;</code>
       */
      public Builder addCourses(
          int index, com.zero.serializabledemo.protobuf._StudentSerializable._Course value) {
        if (coursesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCoursesIsMutable();
          courses_.add(index, value);
          onChanged();
        } else {
          coursesBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       *required指定该字段必须赋值，禁止为空（在v3中该约束被移除）；optional指定字段为可选字段，可以为空，对于optional字段还可以使用[default]指定默认值，如果没有指定，则会使用字段类型的默认值
       * </pre>
       *
       * <code>repeated ._Course courses = 4;</code>
       */
      public Builder addCourses(
          com.zero.serializabledemo.protobuf._StudentSerializable._Course.Builder builderForValue) {
        if (coursesBuilder_ == null) {
          ensureCoursesIsMutable();
          courses_.add(builderForValue.build());
          onChanged();
        } else {
          coursesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       *required指定该字段必须赋值，禁止为空（在v3中该约束被移除）；optional指定字段为可选字段，可以为空，对于optional字段还可以使用[default]指定默认值，如果没有指定，则会使用字段类型的默认值
       * </pre>
       *
       * <code>repeated ._Course courses = 4;</code>
       */
      public Builder addCourses(
          int index, com.zero.serializabledemo.protobuf._StudentSerializable._Course.Builder builderForValue) {
        if (coursesBuilder_ == null) {
          ensureCoursesIsMutable();
          courses_.add(index, builderForValue.build());
          onChanged();
        } else {
          coursesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       *required指定该字段必须赋值，禁止为空（在v3中该约束被移除）；optional指定字段为可选字段，可以为空，对于optional字段还可以使用[default]指定默认值，如果没有指定，则会使用字段类型的默认值
       * </pre>
       *
       * <code>repeated ._Course courses = 4;</code>
       */
      public Builder addAllCourses(
          Iterable<? extends com.zero.serializabledemo.protobuf._StudentSerializable._Course> values) {
        if (coursesBuilder_ == null) {
          ensureCoursesIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, courses_);
          onChanged();
        } else {
          coursesBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <pre>
       *required指定该字段必须赋值，禁止为空（在v3中该约束被移除）；optional指定字段为可选字段，可以为空，对于optional字段还可以使用[default]指定默认值，如果没有指定，则会使用字段类型的默认值
       * </pre>
       *
       * <code>repeated ._Course courses = 4;</code>
       */
      public Builder clearCourses() {
        if (coursesBuilder_ == null) {
          courses_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
          onChanged();
        } else {
          coursesBuilder_.clear();
        }
        return this;
      }
      /**
       * <pre>
       *required指定该字段必须赋值，禁止为空（在v3中该约束被移除）；optional指定字段为可选字段，可以为空，对于optional字段还可以使用[default]指定默认值，如果没有指定，则会使用字段类型的默认值
       * </pre>
       *
       * <code>repeated ._Course courses = 4;</code>
       */
      public Builder removeCourses(int index) {
        if (coursesBuilder_ == null) {
          ensureCoursesIsMutable();
          courses_.remove(index);
          onChanged();
        } else {
          coursesBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <pre>
       *required指定该字段必须赋值，禁止为空（在v3中该约束被移除）；optional指定字段为可选字段，可以为空，对于optional字段还可以使用[default]指定默认值，如果没有指定，则会使用字段类型的默认值
       * </pre>
       *
       * <code>repeated ._Course courses = 4;</code>
       */
      public com.zero.serializabledemo.protobuf._StudentSerializable._Course.Builder getCoursesBuilder(
          int index) {
        return getCoursesFieldBuilder().getBuilder(index);
      }
      /**
       * <pre>
       *required指定该字段必须赋值，禁止为空（在v3中该约束被移除）；optional指定字段为可选字段，可以为空，对于optional字段还可以使用[default]指定默认值，如果没有指定，则会使用字段类型的默认值
       * </pre>
       *
       * <code>repeated ._Course courses = 4;</code>
       */
      public com.zero.serializabledemo.protobuf._StudentSerializable._CourseOrBuilder getCoursesOrBuilder(
          int index) {
        if (coursesBuilder_ == null) {
          return courses_.get(index);  } else {
          return coursesBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <pre>
       *required指定该字段必须赋值，禁止为空（在v3中该约束被移除）；optional指定字段为可选字段，可以为空，对于optional字段还可以使用[default]指定默认值，如果没有指定，则会使用字段类型的默认值
       * </pre>
       *
       * <code>repeated ._Course courses = 4;</code>
       */
      public java.util.List<? extends com.zero.serializabledemo.protobuf._StudentSerializable._CourseOrBuilder> 
           getCoursesOrBuilderList() {
        if (coursesBuilder_ != null) {
          return coursesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(courses_);
        }
      }
      /**
       * <pre>
       *required指定该字段必须赋值，禁止为空（在v3中该约束被移除）；optional指定字段为可选字段，可以为空，对于optional字段还可以使用[default]指定默认值，如果没有指定，则会使用字段类型的默认值
       * </pre>
       *
       * <code>repeated ._Course courses = 4;</code>
       */
      public com.zero.serializabledemo.protobuf._StudentSerializable._Course.Builder addCoursesBuilder() {
        return getCoursesFieldBuilder().addBuilder(
            com.zero.serializabledemo.protobuf._StudentSerializable._Course.getDefaultInstance());
      }
      /**
       * <pre>
       *required指定该字段必须赋值，禁止为空（在v3中该约束被移除）；optional指定字段为可选字段，可以为空，对于optional字段还可以使用[default]指定默认值，如果没有指定，则会使用字段类型的默认值
       * </pre>
       *
       * <code>repeated ._Course courses = 4;</code>
       */
      public com.zero.serializabledemo.protobuf._StudentSerializable._Course.Builder addCoursesBuilder(
          int index) {
        return getCoursesFieldBuilder().addBuilder(
            index, com.zero.serializabledemo.protobuf._StudentSerializable._Course.getDefaultInstance());
      }
      /**
       * <pre>
       *required指定该字段必须赋值，禁止为空（在v3中该约束被移除）；optional指定字段为可选字段，可以为空，对于optional字段还可以使用[default]指定默认值，如果没有指定，则会使用字段类型的默认值
       * </pre>
       *
       * <code>repeated ._Course courses = 4;</code>
       */
      public java.util.List<com.zero.serializabledemo.protobuf._StudentSerializable._Course.Builder> 
           getCoursesBuilderList() {
        return getCoursesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.zero.serializabledemo.protobuf._StudentSerializable._Course, com.zero.serializabledemo.protobuf._StudentSerializable._Course.Builder, com.zero.serializabledemo.protobuf._StudentSerializable._CourseOrBuilder> 
          getCoursesFieldBuilder() {
        if (coursesBuilder_ == null) {
          coursesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.zero.serializabledemo.protobuf._StudentSerializable._Course, com.zero.serializabledemo.protobuf._StudentSerializable._Course.Builder, com.zero.serializabledemo.protobuf._StudentSerializable._CourseOrBuilder>(
                  courses_,
                  ((bitField0_ & 0x00000008) != 0),
                  getParentForChildren(),
                  isClean());
          courses_ = null;
        }
        return coursesBuilder_;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:_Student)
    }

    // @@protoc_insertion_point(class_scope:_Student)
    private static final com.zero.serializabledemo.protobuf._StudentSerializable._Student DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.zero.serializabledemo.protobuf._StudentSerializable._Student();
    }

    public static com.zero.serializabledemo.protobuf._StudentSerializable._Student getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<_Student>
        PARSER = new com.google.protobuf.AbstractParser<_Student>() {
      @Override
      public _Student parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new _Student(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<_Student> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<_Student> getParserForType() {
      return PARSER;
    }

    @Override
    public com.zero.serializabledemo.protobuf._StudentSerializable._Student getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface _CourseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:_Course)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string name = 1;</code>
     */
    String getName();
    /**
     * <code>string name = 1;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>float score = 2;</code>
     */
    float getScore();
  }
  /**
   * <pre>
   *在一个proto文件中可以同时定义多个message类型，生成代码时根据生成代码的目标语言不同，处理的方式不太一样，如Java会针对每个message类型生成一个.java文件
   * </pre>
   *
   * Protobuf type {@code _Course}
   */
  public  static final class _Course extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:_Course)
      _CourseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use _Course.newBuilder() to construct.
    private _Course(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private _Course() {
      name_ = "";
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private _Course(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 21: {

              score_ = input.readFloat();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.zero.serializabledemo.protobuf._StudentSerializable.internal_static__Course_descriptor;
    }

    @Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.zero.serializabledemo.protobuf._StudentSerializable.internal_static__Course_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.zero.serializabledemo.protobuf._StudentSerializable._Course.class, com.zero.serializabledemo.protobuf._StudentSerializable._Course.Builder.class);
    }

    public static final int NAME_FIELD_NUMBER = 1;
    private volatile Object name_;
    /**
     * <code>string name = 1;</code>
     */
    public String getName() {
      Object ref = name_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SCORE_FIELD_NUMBER = 2;
    private float score_;
    /**
     * <code>float score = 2;</code>
     */
    public float getScore() {
      return score_;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
      }
      if (score_ != 0F) {
        output.writeFloat(2, score_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
      }
      if (score_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(2, score_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.zero.serializabledemo.protobuf._StudentSerializable._Course)) {
        return super.equals(obj);
      }
      com.zero.serializabledemo.protobuf._StudentSerializable._Course other = (com.zero.serializabledemo.protobuf._StudentSerializable._Course) obj;

      if (!getName()
          .equals(other.getName())) return false;
      if (Float.floatToIntBits(getScore())
          != Float.floatToIntBits(
              other.getScore())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + SCORE_FIELD_NUMBER;
      hash = (53 * hash) + Float.floatToIntBits(
          getScore());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.zero.serializabledemo.protobuf._StudentSerializable._Course parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zero.serializabledemo.protobuf._StudentSerializable._Course parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zero.serializabledemo.protobuf._StudentSerializable._Course parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zero.serializabledemo.protobuf._StudentSerializable._Course parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zero.serializabledemo.protobuf._StudentSerializable._Course parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zero.serializabledemo.protobuf._StudentSerializable._Course parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zero.serializabledemo.protobuf._StudentSerializable._Course parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.zero.serializabledemo.protobuf._StudentSerializable._Course parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.zero.serializabledemo.protobuf._StudentSerializable._Course parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.zero.serializabledemo.protobuf._StudentSerializable._Course parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.zero.serializabledemo.protobuf._StudentSerializable._Course parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.zero.serializabledemo.protobuf._StudentSerializable._Course parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.zero.serializabledemo.protobuf._StudentSerializable._Course prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *在一个proto文件中可以同时定义多个message类型，生成代码时根据生成代码的目标语言不同，处理的方式不太一样，如Java会针对每个message类型生成一个.java文件
     * </pre>
     *
     * Protobuf type {@code _Course}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:_Course)
        com.zero.serializabledemo.protobuf._StudentSerializable._CourseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.zero.serializabledemo.protobuf._StudentSerializable.internal_static__Course_descriptor;
      }

      @Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.zero.serializabledemo.protobuf._StudentSerializable.internal_static__Course_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.zero.serializabledemo.protobuf._StudentSerializable._Course.class, com.zero.serializabledemo.protobuf._StudentSerializable._Course.Builder.class);
      }

      // Construct using com.zero.serializabledemo.protobuf._StudentSerializable._Course.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        name_ = "";

        score_ = 0F;

        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.zero.serializabledemo.protobuf._StudentSerializable.internal_static__Course_descriptor;
      }

      @Override
      public com.zero.serializabledemo.protobuf._StudentSerializable._Course getDefaultInstanceForType() {
        return com.zero.serializabledemo.protobuf._StudentSerializable._Course.getDefaultInstance();
      }

      @Override
      public com.zero.serializabledemo.protobuf._StudentSerializable._Course build() {
        com.zero.serializabledemo.protobuf._StudentSerializable._Course result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public com.zero.serializabledemo.protobuf._StudentSerializable._Course buildPartial() {
        com.zero.serializabledemo.protobuf._StudentSerializable._Course result = new com.zero.serializabledemo.protobuf._StudentSerializable._Course(this);
        result.name_ = name_;
        result.score_ = score_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.zero.serializabledemo.protobuf._StudentSerializable._Course) {
          return mergeFrom((com.zero.serializabledemo.protobuf._StudentSerializable._Course)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.zero.serializabledemo.protobuf._StudentSerializable._Course other) {
        if (other == com.zero.serializabledemo.protobuf._StudentSerializable._Course.getDefaultInstance()) return this;
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (other.getScore() != 0F) {
          setScore(other.getScore());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.zero.serializabledemo.protobuf._StudentSerializable._Course parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.zero.serializabledemo.protobuf._StudentSerializable._Course) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private Object name_ = "";
      /**
       * <code>string name = 1;</code>
       */
      public String getName() {
        Object ref = name_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       */
      public Builder setName(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private float score_ ;
      /**
       * <code>float score = 2;</code>
       */
      public float getScore() {
        return score_;
      }
      /**
       * <code>float score = 2;</code>
       */
      public Builder setScore(float value) {
        
        score_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float score = 2;</code>
       */
      public Builder clearScore() {
        
        score_ = 0F;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:_Course)
    }

    // @@protoc_insertion_point(class_scope:_Course)
    private static final com.zero.serializabledemo.protobuf._StudentSerializable._Course DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.zero.serializabledemo.protobuf._StudentSerializable._Course();
    }

    public static com.zero.serializabledemo.protobuf._StudentSerializable._Course getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<_Course>
        PARSER = new com.google.protobuf.AbstractParser<_Course>() {
      @Override
      public _Course parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new _Course(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<_Course> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<_Course> getParserForType() {
      return PARSER;
    }

    @Override
    public com.zero.serializabledemo.protobuf._StudentSerializable._Course getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static__Student_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static__Student_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static__Course_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static__Course_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\rstudent.proto\"M\n\010_Student\022\014\n\004name\030\001 \001(" +
      "\t\022\013\n\003sax\030\002 \001(\t\022\013\n\003age\030\003 \001(\005\022\031\n\007courses\030\004" +
      " \003(\0132\010._Course\"&\n\007_Course\022\014\n\004name\030\001 \001(\t\022" +
      "\r\n\005score\030\002 \001(\002B:\n\"com.zero.serializabled" +
      "emo.protobufB\024_StudentSerializableb\006prot" +
      "o3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static__Student_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static__Student_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static__Student_descriptor,
        new String[] { "Name", "Sax", "Age", "Courses", });
    internal_static__Course_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static__Course_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static__Course_descriptor,
        new String[] { "Name", "Score", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
